---
title: "Hawaii Appleseed data visualization"
author: "Charles Hendrickson"
date: "2023-08-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(janitor)
library(plotly)

#set the number of digits to display to 10 decimal places
options(digits = 10)
#turn off scientific notation
options(scipen=999)
```

<div style="height: 50px;"></div>

```{r}
#Total Average Daily Participation - School Year 
df_total <- data.frame(meal_type = c("breakfast", "lunch"),
                  participation = c(32543, 100234))


# Create the bar chart
ggplot(df_total, aes(x = meal_type, y = participation, fill = meal_type)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_text(aes(label = scales::comma_format()(participation)), vjust = 1.5, color = "black", size = 4) +  # Increase vjust value
  labs(title = "Total Average Daily Participation By Meal Type",
       subtitle = "School Year 2018-2019",
       x = "Meal Type",
       y = "Participation",
       fill = "Meal Type") +  # Specify the legend name
  theme_classic() +
  theme(plot.title = element_text(margin = margin(b = 5)),  # Increase space between title and subtitle
        plot.subtitle = element_text(margin = margin(b = 10)),  # Increase space between subtitle and plot
        axis.text.y = element_text(size = 10))  # Adjust the y-axis label size
```

<div style="height: 100px;"></div>

```{r}
#Total Average Daily Participation By Meal Type - School Year 2018-2019			

# Load the data
df_participation <- data.frame(
  Meal_Type = c("Breakfast", "Lunch"),
  Free = c(22822, 55127),
  Reduced = c(2654, 8976),
  Paid = c(6876, 36131)
)

# Convert to a tidy data set
df_participation <- gather(df_participation, key = "Program_Type", value = "Participation", -Meal_Type)

#Make names lowercase 
df_participation <- clean_names(df_participation)

# Create the bar chart with labels at the top of each stack
ggplot(df_participation, aes(x = meal_type, y = participation, fill = program_type)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_text(aes(label = scales::comma_format()(participation)), position = position_stack(vjust = .7), color = "black", size = 4) +  # Position labels at the top
  labs(title = "Total Average Daily Participation By Program Type",
       subtitle = "School Year 2018-2019",
       x = "Meal Type",
       y = "Participation",
       fill = "Program Type") +  # Specify the legend name
  theme_classic() +
  theme(plot.title = element_text(margin = margin(b = 5)),  # Increase space between title and subtitle
        plot.subtitle = element_text(margin = margin(b = 10)),  # Increase space between subtitle and plot
        axis.text.y = element_text(size = 10))  # Adjust the y-axis label size


```

<div style="height: 100px;"></div>

```{r, warning=FALSE}
#Total Average Daily Participation By Program Type - 6.8% increase for lunch and 12.1% increase for breakfast over 2018-19
# Create the tidy dataframe
df_participation_increase <- data.frame(
  Meal_Type = c("Breakfast", "Lunch"),
  Free = c(25583, 58876),
  Reduced = c(2975, 9586),
  Paid = c(7708, 38588)
)

# Convert to a tidy format
df_participation_increase <- pivot_longer(df_participation_increase, cols = -Meal_Type, names_to = "Program_Type", values_to = "Participation")

#Make columns lower case
df_participation_increase <- clean_names(df_participation_increase)

# Create the bar chart with labels at the top of each stack
ggplot(df_participation_increase, aes(x = meal_type, y = participation, fill = program_type)) +
  geom_bar(stat = "identity", width = 0.6) +
  geom_text(aes(label = scales::comma_format()(participation)), position = position_stack(vjust = .7), color = "black", size = 4) +  # Position labels at the top
  labs(title = "Total Average Daily Participation By Program Type",
       subtitle = "6.8% Increase for Lunch and 12.1% Increase for Breakfast over 2018-19 School Year",
       x = "Meal Type",
       y = "Participation",
       fill = "Program Type") +  # Specify the legend name
  theme_classic() + 
  theme(plot.title = element_text(margin = margin(b = 5)),  # Increase space between title and subtitle
        plot.subtitle = element_text(margin = margin(b = 20)),  # Increase space between subtitle and plot
        axis.text.y = element_text(size = 10))  # Adjust the y-axis label size
```


```{r}
#DIFFERENCE Between Actual ADP and 6.8%/12.1% Increase (# of Students)
# Given data in a matrix
data_matrix <- matrix(
  c(2761, 321, 832, 3749, 610, 2457),
  ncol = 3,
  byrow = TRUE,
  dimnames = list(c("Breakfast", "Lunch"), c("Free", "Reduced", "Paid"))
)

# Convert the matrix to a data frame
df_difference <- as.data.frame(data_matrix)

# Remove commas from the numbers and convert to numeric
for (col in names(df_difference)) {
  df_difference[[col]] <- as.numeric(gsub(",", "", df_difference[[col]]))
}

# Add the Meal_Type column
df_difference$Meal_Type <- rownames(df_difference)

# Convert to a tidy data frame
df_difference <- pivot_longer(df_difference, cols = c("Free", "Reduced", "Paid"), names_to = "Program_Type", values_to = "participation_difference")

#make column names lowercase
df_difference <- clean_names(df_difference)
```


```{r}
# Add a new column to indicate the source for tidy_data
df_participation$provision <- "Actual ADP"

# Add a new column to indicate the source for tidy_df
df_participation_increase$provision <- "Increased ADP"

# Combine the data frames
participation_combined <- rbind(df_participation, df_participation_increase)

# Merge the df_difference data frame with the combined data frame and add a difference column 
participation_combined <- merge(participation_combined, df_difference, by = c("meal_type", "program_type"))

# Set participation_difference to 'NA' for rows where provision is 'Current'
participation_combined$participation_difference <- ifelse(participation_combined$provision == "Actual ADP", NA, participation_combined$participation_difference)

```

<div style="height: 100px;"></div>

```{r, warning=FALSE}
# Create the bar chart with single label for participation_difference
ggplot(participation_combined, aes(x = meal_type, y = participation, fill = provision)) +
  geom_bar(stat = "identity", position = "dodge", width = 0.6, color = "black") +
  facet_grid(~program_type) +
  labs(title = "Comparison of Actual and Increased Total Average Daily Participation (ADP)",
       subtitle = "6.8% Increase for Lunch and 12.1% Increase for Breakfast over 2018-19 School Year",
       x = "Meal Type",
       y = "Participation",
       caption = "*Values represent the difference between actual ADP and ADP with 6.8% and 12.1% increase.",
       fill = "Program Type") +
  stat_summary(
    aes(label = round(participation_difference, 2)),
    fun = mean,
    geom = "text",
    vjust = -0.5,
    position = position_dodge(width = 0.6),
    show.legend = FALSE
  ) +
  annotate("text", x = 1.5, y = 65000, label = "", size = 5, color = "blue") +
  theme_classic() +
  theme(plot.title = element_text(size = 18)) +  # Increase the font size of the title to 17
  theme(plot.caption = element_text(hjust = 0)) # set the left align here
```


```{r}
#October 2022 NSLP Eligibility By Meal Type - School Year 2021-2022
# Create a data frame with the provided data
nslp_eligibility_2022_data <- data.frame(
  Category = c("DOE Public Schools", "Charter Schools - All**", "Charter Schools - Non-CEP", "Private Non-Profit"),
  `Free Eligible` = c(74107, 4919, 321, 77),
  `Reduced Price Eligible` = c(9192, 87, 87, 287),
  `Paid Eligible` = c(76806, 1959, 1429, 372),
  `% Free and Reduced Enrolled` = c(57.6, 67, NA, 22.2)
)

# Make column names lowercase and Rename column names
nslp_eligibility_2022_data <- clean_names(nslp_eligibility_2022_data) %>% rename(percent_free_and_reduced_enrolled = x_free_and_reduced_enrolled, school_type = category)

# Select columns in the correct order before pivoting
nslp_eligibility_2022_data <- nslp_eligibility_2022_data %>%
  select(percent_free_and_reduced_enrolled, school_type, everything())

# Make the data frame tidy
nslp_eligibility_2022_data <- pivot_longer(nslp_eligibility_2022_data, 
                                           cols = starts_with(c("free", "reduced_price", "paid")), 
                                           names_to = "program_type", 
                                           values_to = "participation")


# Replace values in the "program_type" column 
replace_program_type <- function(df) {
  # Define a function to map the old values to the new ones
  map_program_type <- function(value) {
    if (value == "free_eligible") {
      return("free")
    } else if (value == "reduced_price_eligible") {
      return("reduced")
    } else if (value == "paid_eligible") {
      return("paid")
    } else {
      return(value)
    }
  }
  
  # Apply the mapping function to the "program_type" column
  df$program_type <- sapply(df$program_type, map_program_type)
  
  return(df)
}

# Call the function and update the data frame
nslp_eligibility_2022_data <- replace_program_type(nslp_eligibility_2022_data)

```

<div style="height: 100px;"></div>

```{r}
# Create the bar chart
ggplot(nslp_eligibility_2022_data, aes(x = program_type, y = participation, fill = school_type)) +
  geom_bar(stat = "identity", position = "dodge", color = "black") +
  facet_wrap(~ school_type, scales = "free", ncol = 1) +
  labs(title = "October 2022 National School Lunch Program Eligibility By School Type",
       subtitle = "School Year 2021-2022",
       x = "Program Type",
       y = "Eligibility",
       fill = "School Type") +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text = element_blank())

```

<div style="height: 100px;"></div>

```{r}
ggplot(nslp_eligibility_2022_data, aes(x = program_type, y = participation, fill = school_type)) +
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.6) +
  facet_grid(~school_type) +
  labs(title = "October 2022 National School Lunch Program Eligibility By School Type",
       subtitle = "School Year 2021-2022",
       x = "Program Type",
       y = "Eligibility",
       fill = "School Type") +
  theme(strip.background = element_blank(),
        strip.text = element_blank()) + 
  geom_text(
    aes(label = participation),
    colour = "black", size = 3,
    vjust = -0.2,
    position = position_dodge(width = 0.6),
    show.legend = FALSE
  ) +
  theme_classic() +
  theme(strip.background = element_blank(),
        strip.text = element_blank()) +
  theme(plot.title = element_text(size = unit(16, "pt")))  # Increase the font size of the title to 18
```


```{r}
#Cost Analysis (Public Schools Only)

#Create a data frame
cost_analysis_data_pso <- data.frame(
  Program_Type = c("Paid", "Reduced","Reduced", "Paid", "NA", "NA", "NA"),
  Meal_Type = c("Lunch", "Lunch", "Breakfast", "Breakfast", "Breakfast Only", "Lunch Only", "Breakfast + Lunch"),
  SY21_22_HCNP_Eligibility_Data = c(36359960.40, 661824.00, 496368.00, 15207588.00, 15703956.00, 37021784.40, 52725740.40),
  FRAC_ADP_SY18_19_Data = c(16113962.24, 639582.05, 138049.54, 926632.28, 1064681.82, 16753544.29, 17818226.11),
  Increase_6.8_12.1_Data = c(17591027.05, 683954.50, 155959.24, 1243241.21, 1399200.44, 18274981.54, 19674181.99)
)

# # Remove row values that were 'totals' or 'sums' of other rows
# tidy_cost_analysis_data_pso <- data.frame(
#   Program_Type = c("Paid", "Reduced","Reduced", "Paid"),
#   Meal_Type = c("Lunch", "Lunch", "Breakfast", "Breakfast"),
#   SY21_22_HCNP = c(36359960.40, 661824.00, 496368.00, 15207588.00),
#   FRAC_ADP_SY18_19 = c(16113962.24, 639582.05, 138049.54, 926632.28),
#   Increase_6.8_12.1 = c(17591027.05, 683954.50, 155959.24, 1243241.21)
# )

# Make column names lowercase
cost_analysis_data_pso <- clean_names(cost_analysis_data_pso)

# Make the data frame Tidy
cost_analysis_data_pso <- pivot_longer(cost_analysis_data_pso, 
                                           cols = starts_with(c("sy21_", "frac_", "increase")), 
                                           names_to = "budget_type", 
                                           values_to = "cost")


# Create new "cost_type" column
cost_analysis_data_pso$cost_type <- cost_analysis_data_pso$budget_type

# Add values into column
create_cost_type <- function(df) {
  # Define a function to create new values
  cost_type <- function(budget_type) {
    if (budget_type == "sy21_22_hcnp_eligibility_data") {
      return("Highest Cost")
    } else if (budget_type == "frac_adp_sy18_19_data") {
      return("Lowest Cost")
    } else if (budget_type == "increase_6_8_12_1_data") {
      return("Expected Cost")
    } else {
      return(budget_type)
    }
  }
  
  # Apply the mapping function to the "program_type" column
  cost_analysis_data_pso$cost_type <- sapply(cost_analysis_data_pso$cost_type, cost_type)
  
  return(cost_analysis_data_pso)
}

# Call the function and update the data frame
cost_analysis_data_pso <- create_cost_type(cost_analysis_data_pso)

```

<div style="height: 100px;"></div>

```{r}
# Filter for lunch only, breakfast only, and breakfast+lunch
cost_analysis_data_pso_filtered <- cost_analysis_data_pso  %>% group_by(meal_type) %>% filter(any(meal_type == c("Breakfast Only", "Lunch Only", "Breakfast + Lunch")))


#Stacked bar chart with breakfast+lunch, luch only, and breakfast only. 3X Most it could cost, least it could cost, and expected cost.
ggplot(data = cost_analysis_data_pso_filtered, aes(x = reorder(cost_type, + cost), y = cost, fill = meal_type)) +
  geom_bar(stat = "identity", position = "stack")+
  labs(title = "Cost Analysis of School Meal Programs",
       subtitle = "Public Schools Only",
       x = "Outcomes",
       y = "Cost",
       caption = "The lowest cost assumes meal fees are the same and 0% paid and reduced-price student participation
from charter schools. The expected cost assumes a 6.8% increase for lunch costs and a 12.1% increase 
for breakfast costs and 0% paid and reduced-price student participation from charter schools. The highest 
cost assumes 100% participation for DOE and charter schools and meal fees are the same.") +
  theme_classic() +
  theme(plot.caption = element_text(hjust = 0)) # set the left align here


```

<div style="height: 100px;"></div>

```{r}
#Stacked bar chart with breakfast+lunch, luch only, and breakfast only. 3X Most it could cost, least it could cost, and expected cost.
ggplot(data = cost_analysis_data_pso_filtered, aes(x = reorder(cost_type, + cost), y = cost, fill = meal_type)) +
  geom_bar(stat = "identity", position = position_dodge(width = .8), width = 0.6) +
  labs(title = "Cost Analysis of School Meal Programs",
       subtitle = "Public Schools Only",
       x = "Outcomes",
       y = "Cost") +
  theme_classic()


```

<div style="height: 100px;"></div>


























